[Service]
Environment=TERM=vt100
ExecStart=
ExecStart=-/bin/bash --login
Restart=no
StandardInput=tty
StandardOutput=tty
StandardError=tty
TTYPath=/dev/tty1
TTYReset=yes
TTYVHangup=yes
TTYVTDisallocate=no
