# HippOS OS-level settings defaults.
# User overrides are written to /userdata/system/hippos.conf by hippos-settings.

system.session=es
system.boot_session=es
system.desktop=lxqt
system.hostname=hippos
system.ssh.enabled=true
system.suspendmode=suspend
system.cpu.governor=performance
enable_bootloader=true
audio.device=default
audio.volume=80
display.output=
display.resolution=preferred
display.rotate=0
global.powermode=balanced
global.batterymode=balanced
global.tdp=
gpu.nvidia-driver=auto
gpu.nvidia-prime=true
gpu.radeon-prime=true
gpu.intel-prime=true
global.retroachievements=false
global.retroachievements.hardcore=false
global.smooth=false
global.integerscale=false
global.use_guns=true
global.use_wheels=true
global.shaderset=none
global.mangohud=false
content.catalog_url=https://hippos-linux.org/store/content-catalog.json
network.roms.enabled=true
network.roms.discovery.enabled=true
network.roms.discovery.auto_mount=true
global.vkbasalt=false
steam.deckmode=false
windows.dxvk=true
windows.fsync=true
windows.esync=false
crt.enabled=false
crt.monitor_profile=generic_15
crt.output=
crt.interlace=true
crt.super_width=2560
crt.dotclock_min=0.0
crt.boot_resolution=640x480i_15
crt.videomode=
crt.tate_mode=off
