from __future__ import annotations

import configparser
from pathlib import Path

from emulatorlauncher_impl import (
    _log,
    BIOS,
    CACHE,
    CONFIGS,
    DOLPHIN_CONFIG_DIR,
    DOLPHIN_GFX_INI,
    DOLPHIN_INI,
    DOLPHIN_QT_INI,
    DUCKSTATION_CONFIG_DIR,
    DUCKSTATION_SETTINGS,
    FLYCAST_CONFIG_DIR,
    FLYCAST_EMU_CFG,
    LaunchContext,
    MAME_CONFIG_DIR,
    MAME_INI,
    MAME_ROMS,
    MUPEN_CONFIG_DIR,
    MUPEN_CUSTOM,
    SAVES,
    SCREENSHOTS,
    _build_game_env,
    _conf_bool,
    _conf_value,
    _display_resolution_from_conf,
    _find_emulator_bin,
    _load_effective_hippos_conf,
    _load_hippos_conf,
    _new_ini_parser,
    _run_game_command,
    _write_dolphin_controller_configs,
    _write_mupen_controller_configs,
    _ensure_section,
    generate_sdl_game_controller_config,
    _gun_type,
    _load_es_input_configs,
    _pick_es_profile,
)


def _write_mame_config(conf: dict[str, str]) -> None:
    MAME_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    (SAVES / 'mame').mkdir(parents=True, exist_ok=True)

    lines: list[tuple[str, str]] = [
        ('inipath',            f'{MAME_CONFIG_DIR};/etc/mame'),
        ('rompath',            f'{MAME_ROMS};/usr/share/games/mame/roms'),
        ('cfg_directory',      str(MAME_CONFIG_DIR / 'cfg')),
        ('nvram_directory',    str(SAVES / 'mame' / 'nvram')),
        ('snapshot_directory', str(SCREENSHOTS)),
        ('state_directory',    str(SAVES / 'mame')),
        ('video',              'opengl'),
        ('window',             '0'),
        ('mouse',              '1'),
    ]

    if Path('/etc/switchres.ini').exists():
        profile    = conf.get('crt.monitor_profile', 'generic_15')
        sw         = conf.get('crt.super_width',     '2560')
        dotclk     = conf.get('crt.dotclock_min',    '0.0')
        lines += [
            ('switchres',    '1'),
            ('monitor',      profile),
            ('super_width',  sw),
            ('dotclock_min', dotclk),
        ]

    col = max(len(k) for k, _ in lines) + 3
    with MAME_INI.open('w') as fh:
        fh.write('# Generated by emulatorlauncher — do not edit manually.\n')
        for key, value in lines:
            fh.write(f'{key:<{col}}{value}\n')



def launch_mame(ctx: LaunchContext) -> int:
    bin_path = _find_emulator_bin('mame')
    if bin_path is None:
        return 1

    conf = _load_hippos_conf()
    _write_mame_config(conf)
    (SAVES / ctx.system).mkdir(parents=True, exist_ok=True)

    from emulatorlauncher_mame_controllers import generate_mame_pads_config
    cfg_dir = MAME_CONFIG_DIR / 'cfg'
    try:
        generate_mame_pads_config(cfg_dir, ctx, conf)
    except Exception as exc:
        _log.warning("MAME controller config failed: %s", exc)

    game_flags: list[str] = []
    if ctx.lightgun:
        game_flags += ['-lightgunprovider', 'udev', '-lightgun_device', 'lightgun', '-adstick_device', 'lightgun']
    elif ctx.wheel:
        game_flags += ['-dial_device', 'mouse', '-trackball_device', 'mouse', '-paddle_device', 'mouse', '-positional_device', 'mouse', '-mouse_device', 'mouse', '-ui_mouse']

    cmd = [str(bin_path), '-inipath', f'{MAME_CONFIG_DIR};/etc/mame', *game_flags, str(ctx.rom)]
    env = _build_game_env(conf, ctx)
    result = _run_game_command(ctx, 'mame', cmd, env)
    return result.returncode



def _write_dolphin_config(ctx: LaunchContext) -> None:
    conf = _load_effective_hippos_conf()
    profiles = []
    try:
        from emulatorlauncher_impl import _load_es_input_configs
        profiles = _load_es_input_configs()
    except Exception:
        profiles = []
    DOLPHIN_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    parser = _new_ini_parser()
    if DOLPHIN_INI.exists():
        parser.read(DOLPHIN_INI)

    _ensure_section(parser, 'General')
    _ensure_section(parser, 'Core')
    _ensure_section(parser, 'DSP')
    _ensure_section(parser, 'Interface')
    _ensure_section(parser, 'Analytics')
    _ensure_section(parser, 'Display')
    _ensure_section(parser, 'GBA')

    qt_parser = _new_ini_parser()
    if DOLPHIN_QT_INI.exists():
        qt_parser.read(DOLPHIN_QT_INI)
    _ensure_section(qt_parser, 'Emulation')
    qt_parser.set('Emulation', 'StateSlot', _conf_value(conf, 'state_slot', '1'))
    with DOLPHIN_QT_INI.open('w', encoding='utf-8') as fh:
        qt_parser.write(fh)

    parser.set('General', 'ISOPath0', '/userdata/roms/wii')
    parser.set('General', 'ISOPath1', '/userdata/roms/gamecube')
    parser.set('General', 'ISOPaths', '2')
    parser.set('General', 'AutoIncrementSlot', str(_conf_bool(conf, 'incrementalsavestates', True)))
    parser.set('Analytics', 'PermissionAsked', 'True')
    parser.set('Interface', 'UsePanicHandlers', 'False')
    parser.set('Interface', 'OnScreenDisplayMessages', 'True' if _conf_bool(conf, 'ShowDpMsg', False) or _conf_bool(conf, 'global.retroachievements', False) else 'False')
    parser.set('Interface', 'ConfirmStop', 'False')
    parser.remove_option('Display', 'RenderToMain')
    parser.set('Display', 'Fullscreen', 'True')

    parser.set('Core', 'EnableCheats', str(_conf_bool(conf, 'dolphin_cheats_enabled', _conf_bool(conf, 'global.enable_cheats', False))))
    parser.set('Core', 'FastDiscSpeed', str(_conf_bool(conf, 'enable_fastdisc', False)))
    parser.set('Core', 'CPUThread', str(_conf_bool(conf, 'dual_core', True)))
    parser.set('Core', 'SyncGPU', str(_conf_bool(conf, 'gpu_sync', False)))
    parser.set('Core', 'SelectedLanguage', _conf_value(conf, 'gamecube_language', '0'))
    parser.set('Core', 'MMU', str(_conf_bool(conf, 'enable_mmu', False)))
    parser.set('Core', 'WiimoteContinuousScanning', 'True')
    parser.set('Core', 'AutoDiscChange', 'True')
    parser.set('Core', 'SkipIPL', 'True' if _conf_bool(conf, 'dolphin_SkipIPL', True) else 'False')

    gfx_backend = _conf_value(conf, 'gfxbackend', 'OGL').lower()
    parser.set('Core', 'GFXBackend', 'Vulkan' if gfx_backend == 'vulkan' else 'OGL')
    parser.set('Core', 'DPL2Decoder', 'True' if _conf_bool(conf, 'dplii', False) else 'False')
    parser.set('Core', 'DSPHLE', 'False' if _conf_bool(conf, 'dplii', False) else 'True')
    parser.set('DSP', 'Backend', 'Cubeb')
    parser.set('DSP', 'EnableJIT', 'True' if _conf_bool(conf, 'dplii', False) else 'False')

    if ctx.system == 'gamecube':
        parser.set('Core', 'SIDevice0', '8' if ctx.wheel else '6')
        parser.set('Core', 'SIDevice1', '6')
    elif ctx.system == 'triforce':
        parser.set('Core', 'SIDevice0', '8' if ctx.wheel else '6')
        parser.set('Core', 'SIDevice1', '8' if ctx.wheel else '6')
    else:
        for idx in range(4):
            parser.set('Core', f'SIDevice{idx}', '6')

    if ctx.wheel and ctx.system in ('gamecube', 'triforce'):
        parser.set('Core', 'SIDevice0', '8')
        if ctx.system == 'triforce':
            parser.set('Core', 'SIDevice1', '8')

    gfx_parser = _new_ini_parser()
    if DOLPHIN_GFX_INI.exists():
        gfx_parser.read(DOLPHIN_GFX_INI)
    _ensure_section(gfx_parser, 'Settings')
    _ensure_section(gfx_parser, 'Hardware')
    gfx_parser.set('Settings', 'AspectRatio', _conf_value(conf, 'dolphin_aspect_ratio', '0'))
    gfx_parser.set('Settings', 'ShowFPS', 'True' if _conf_bool(conf, 'show_fps', False) else 'False')
    hires_textures = 'True' if _conf_bool(conf, 'hires_textures', False) else 'False'
    gfx_parser.set('Settings', 'HiresTextures', hires_textures)
    gfx_parser.set('Settings', 'CacheHiresTextures', hires_textures)
    gfx_parser.set('Settings', 'wideScreenHack', 'True' if _conf_bool(conf, 'widescreen_hack', False) else 'False')

    with DOLPHIN_INI.open('w', encoding='utf-8') as fh:
        parser.write(fh)
    with DOLPHIN_GFX_INI.open('w', encoding='utf-8') as fh:
        gfx_parser.write(fh)

    _write_dolphin_controller_configs(ctx, profiles)



def launch_dolphin(ctx: LaunchContext) -> int:
    bin_path = _find_emulator_bin('dolphin-emu') or _find_emulator_bin('dolphin')
    if bin_path is None:
        return 1
    (SAVES / ctx.system).mkdir(parents=True, exist_ok=True)
    _write_dolphin_config(ctx)
    conf = _load_hippos_conf()
    cmd = [str(bin_path), str(ctx.rom)]
    env = _build_game_env(conf, ctx)
    result = _run_game_command(ctx, 'dolphin', cmd, env)
    return result.returncode




def _lightgun_color(index: int) -> str:
    palette = (
        '-1073741571',  # Red
        '-1057153792',  # Blue
        '-1073479933',  # Green
        '-1056964609',  # White
    )
    return palette[(index - 1) % len(palette)]

def _write_mupen_config(ctx: LaunchContext) -> None:
    conf = _load_effective_hippos_conf()
    profiles = _load_es_input_configs()
    MUPEN_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    parser = _new_ini_parser()
    if MUPEN_CUSTOM.exists():
        parser.read(MUPEN_CUSTOM)

    _ensure_section(parser, 'Core')
    _ensure_section(parser, 'Audio-SDL')
    _ensure_section(parser, 'Video-General')
    _ensure_section(parser, 'Video-Glide64mk2')
    _ensure_section(parser, 'Video-GLideN64')
    _ensure_section(parser, 'Video-Rice')
    _ensure_section(parser, '64DD')

    parser.set('Core', 'Version', '1.01')
    parser.set('Core', 'ScreenshotPath', str(SCREENSHOTS))
    parser.set('Core', 'SaveStatePath', str(SAVES / 'n64'))
    parser.set('Core', 'SaveSRAMPath', str(SAVES / 'n64'))
    parser.set('Core', 'SharedDataPath', str(MUPEN_CONFIG_DIR))
    parser.set('Core', 'SaveFilenameFormat', '1000')
    parser.set('Core', 'DisableExtraMem', str(_conf_bool(conf, 'mupen64plus_DisableExtraMem', False)))

    state_slot = _conf_value(conf, 'state_slot', '')
    if state_slot:
        parser.set('Core', 'CurrentStateSlot', state_slot)
    parser.set('Core', 'AutoStateSlotIncrement', str(_conf_bool(conf, 'incrementalsavestates', True)))

    parser.set('Audio-SDL', 'AUDIO_SYNC', str(_conf_bool(conf, 'mupen64plus_AudioSync', False)))
    match _conf_value(conf, 'mupen64plus_AudioBuffer', 'Medium'):
        case 'Very High':
            primary_buffer_size = '16384'
            primary_buffer_target = '4096'
            secondary_buffer_size = '2048'
        case 'High':
            primary_buffer_size = '16384'
            primary_buffer_target = '2048'
            secondary_buffer_size = '1024'
        case 'Low':
            primary_buffer_size = '4096'
            primary_buffer_target = '1024'
            secondary_buffer_size = '512'
        case _:
            primary_buffer_size = '8192'
            primary_buffer_target = '2048'
            secondary_buffer_size = '1024'
    parser.set('Audio-SDL', 'PRIMARY_BUFFER_SIZE', primary_buffer_size)
    parser.set('Audio-SDL', 'PRIMARY_BUFFER_TARGET', primary_buffer_target)
    parser.set('Audio-SDL', 'SECONDARY_BUFFER_SIZE', secondary_buffer_size)

    display_resolution = _display_resolution_from_conf(conf)
    if display_resolution is not None:
        width, height = display_resolution
        if width < height:
            width, height = height, width
        parser.set('Video-General', 'ScreenWidth', str(width))
        parser.set('Video-General', 'ScreenHeight', str(height))
    parser.set('Video-General', 'Version', '1')
    parser.set('Video-General', 'Fullscreen', 'False')
    parser.set('Video-General', 'VerticalSync', 'True')

    parser.set('Video-Rice', 'Version', '1')
    parser.set('Video-Glide64mk2', 'Version', '1')

    mupen_ratio = _conf_value(conf, 'mupen64plus_ratio', '')
    ratio = _conf_value(conf, 'global.ratio', 'core')
    if mupen_ratio == '16/9' or (not mupen_ratio and ratio == '16/9'):
        adjust_aspect = '1'
        aspect = '1'
        aspect_ratio = '2'
    elif mupen_ratio == '4/3' or (not mupen_ratio and ratio == '4/3'):
        adjust_aspect = '0'
        aspect = '0'
        aspect_ratio = '1'
    else:
        adjust_aspect = '-1'
        aspect = '-1'
        aspect_ratio = '3'
    parser.set('Video-Glide64mk2', 'adjust_aspect', adjust_aspect)
    parser.set('Video-Glide64mk2', 'aspect', aspect)
    parser.set('Video-GLideN64', 'AspectRatio', aspect_ratio)

    match _conf_value(conf, 'mupen64plus_Mipmapping', '0'):
        case '1':
            filtering = '0'
        case '2':
            filtering = '1'
        case '3':
            filtering = '2'
        case _:
            filtering = '-1'
    parser.set('Video-Rice', 'Mipmapping', _conf_value(conf, 'mupen64plus_Mipmapping', '0'))
    parser.set('Video-Glide64mk2', 'filtering', filtering)

    anisotropic = _conf_value(conf, 'mupen64plus_Anisotropic', '0')
    parser.set('Video-Rice', 'AnisotropicFiltering', anisotropic)
    parser.set('Video-Glide64mk2', 'wrpAnisotropic', '1' if anisotropic == '0' else anisotropic)

    antialiasing = _conf_value(conf, 'mupen64plus_AntiAliasing', '0')
    parser.set('Video-Rice', 'MultiSampling', antialiasing)
    parser.set('Video-Glide64mk2', 'wrpAntiAliasing', antialiasing)

    load_hires_textures = _conf_bool(conf, 'mupen64plus_LoadHiResTextures', False)
    parser.set('Video-Rice', 'LoadHiResTextures', str(load_hires_textures))
    parser.set('Video-Glide64mk2', 'ghq_hirs', '1' if load_hires_textures else '0')
    parser.set('Video-Rice', 'TextureEnhancement', _conf_value(conf, 'mupen64plus_TextureEnhancement', '0'))

    autoframeskip = '0'
    parser.set('Video-Glide64mk2', 'autoframeskip', '0')
    match _conf_value(conf, 'mupen64plus_frameskip', '0'):
        case 'automatic':
            autoframeskip = '1'
            maxframeskip = '5'
        case '0':
            maxframeskip = '0'
        case _ as frameskip:
            maxframeskip = frameskip
    parser.set('Video-Glide64mk2', 'autoframeskip', autoframeskip)
    parser.set('Video-Glide64mk2', 'maxframeskip', maxframeskip)
    parser.set('Video-Glide64mk2', 'fb_read_always', _conf_value(conf, 'mupen64plus_fb_read_always', '-1'))

    if ctx.system == 'n64dd':
        parser.set('64DD', 'IPL-ROM', str(BIOS / '64DD_IPL.bin'))
    else:
        parser.set('64DD', 'IPL-ROM', '')
    parser.set('64DD', 'Disk', '')

    parser.set('Video-Rice', 'ShowFPS', 'True' if _conf_bool(conf, 'show_fps', False) else 'False')
    parser.set('Video-Glide64mk2', 'show_fps', '4' if _conf_bool(conf, 'show_fps', False) else '8')

    for section_option, user_config_value in conf.items():
        if not section_option.startswith('mupen64plus.'):
            continue
        custom_section, _, custom_option = section_option.partition('.')
        _ensure_section(parser, custom_section)
        parser.set(custom_section, custom_option, str(user_config_value))

    _write_mupen_controller_configs(ctx, profiles, parser, conf)

    with MUPEN_CUSTOM.open('w', encoding='utf-8') as fh:
        parser.write(fh)

    _log.info("Wrote Mupen config: %s", MUPEN_CUSTOM)


def _launch_mupen64plus_qt(ctx: LaunchContext) -> int:
    bin_path = _find_emulator_bin('mupen64plus-qt')
    if bin_path is None:
        _log.error("mupen64plus-qt not found")
        return 1

    (SAVES / ctx.system).mkdir(parents=True, exist_ok=True)
    _write_mupen_config(ctx)

    conf = _load_hippos_conf()
    cmd = [str(bin_path), str(ctx.rom)]
    _log.info("Launching mupen64plus-qt: %s", ' '.join(cmd))
    env = _build_game_env(conf, ctx)
    result = _run_game_command(ctx, 'mupen64', cmd, env)
    return result.returncode


def _lightgun_color(index: int) -> str:
    palette = (
        '-1073741571',  # Red
        '-1057153792',  # Blue
        '-1073479933',  # Green
        '-1056964609',  # White
    )
    return palette[(index - 1) % len(palette)]


def _write_duckstation_config(ctx: LaunchContext) -> None:
    conf = _load_effective_hippos_conf()
    DUCKSTATION_CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    settings = _new_ini_parser()
    if DUCKSTATION_SETTINGS.exists():
        settings.read(DUCKSTATION_SETTINGS, encoding='utf-8')

    for section in ('Main', 'ControllerPorts', 'Console', 'BIOS', 'CPU', 'GPU', 'Display', 'Audio', 'GameList', 'Hotkeys', 'CDROM', 'UI'):
        _ensure_section(settings, section)

    settings.set('Main', 'SettingsVersion', '3')
    settings.set('Main', 'InhibitScreensaver', 'true')
    settings.set('Main', 'StartPaused', 'false')
    settings.set('Main', 'StartFullscreen', 'true')
    settings.set('Main', 'PauseOnFocusLoss', 'false')
    settings.set('Main', 'PauseOnMenu', 'true')
    settings.set('Main', 'ConfirmPowerOff', 'false')
    settings.set('Main', 'ApplyGameSettings', 'true')
    settings.set('Main', 'SetupWizardIncomplete', 'false')
    settings.set('Main', 'EmulationSpeed', _conf_value(conf, 'duckstation_clocking', '1'))
    settings.set('Main', 'SyncToHostRefreshRate', _conf_value(conf, 'duckstation_hrr', 'false'))
    settings.set('Main', 'Language', 'English')
    settings.set('Main', 'RewindEnable', 'true' if _conf_bool(conf, 'global.rewind', False) else 'false')

    settings.set('ControllerPorts', 'ControllerSettingsMigrated', 'true')
    settings.set('ControllerPorts', 'PointerXScale', '8')
    settings.set('ControllerPorts', 'PointerYScale', '8')
    settings.set('ControllerPorts', 'PointerXInvert', 'false')
    settings.set('ControllerPorts', 'PointerYInvert', 'false')

    # Clear all Pad sections then rebuild from connected controllers
    for i in range(1, 9):
        pad = f'Pad{i}'
        if settings.has_section(pad):
            settings.remove_section(pad)
        settings.add_section(pad)
        settings.set(pad, 'Type', 'None')

    # MultitapMode: auto-detect from controller count
    multitap = 'Disabled'
    for nplayer in range(1, len(ctx.controllers[:8]) + 1):
        if nplayer > 2:
            multitap = 'Port1Only'
        if nplayer > 4:
            multitap = 'BothPorts'
    settings.set('ControllerPorts', 'MultitapMode', multitap)

    # Per-pad SDL button mappings
    for nplayer, ctrl in enumerate(ctx.controllers[:8], start=1):
        pad_num  = f'Pad{nplayer}'
        sdl_num  = f'SDL-{ctrl.index}'
        ctrl_key = f'duckstation_Controller{nplayer}'
        ctrl_type = conf.get(ctrl_key, 'DigitalController')

        settings.set(pad_num, 'Type',        ctrl_type)
        settings.set(pad_num, 'Up',          f'{sdl_num}/DPadUp')
        settings.set(pad_num, 'Right',       f'{sdl_num}/DPadRight')
        settings.set(pad_num, 'Down',        f'{sdl_num}/DPadDown')
        settings.set(pad_num, 'Left',        f'{sdl_num}/DPadLeft')
        settings.set(pad_num, 'Triangle',    f'{sdl_num}/Y')
        settings.set(pad_num, 'Circle',      f'{sdl_num}/B')
        settings.set(pad_num, 'Cross',       f'{sdl_num}/A')
        settings.set(pad_num, 'Square',      f'{sdl_num}/X')
        settings.set(pad_num, 'Select',      f'{sdl_num}/Back')
        settings.set(pad_num, 'Start',       f'{sdl_num}/Start')
        settings.set(pad_num, 'L1',          f'{sdl_num}/LeftShoulder')
        settings.set(pad_num, 'R1',          f'{sdl_num}/RightShoulder')
        settings.set(pad_num, 'L2',          f'{sdl_num}/+LeftTrigger')
        settings.set(pad_num, 'R2',          f'{sdl_num}/+RightTrigger')
        settings.set(pad_num, 'L3',          f'{sdl_num}/LeftStick')
        settings.set(pad_num, 'R3',          f'{sdl_num}/RightStick')
        settings.set(pad_num, 'LLeft',       f'{sdl_num}/-LeftX')
        settings.set(pad_num, 'LRight',      f'{sdl_num}/+LeftX')
        settings.set(pad_num, 'LDown',       f'{sdl_num}/+LeftY')
        settings.set(pad_num, 'LUp',         f'{sdl_num}/-LeftY')
        settings.set(pad_num, 'RLeft',       f'{sdl_num}/-RightX')
        settings.set(pad_num, 'RRight',      f'{sdl_num}/+RightX')
        settings.set(pad_num, 'RDown',       f'{sdl_num}/+RightY')
        settings.set(pad_num, 'RUp',         f'{sdl_num}/-RightY')
        settings.set(pad_num, 'SmallMotor',  f'{sdl_num}/SmallMotor')
        settings.set(pad_num, 'LargeMotor',  f'{sdl_num}/LargeMotor')
        settings.set(pad_num, 'VibrationBias', '8')

        if ctrl_type == 'AnalogController':
            settings.set(pad_num, 'AnalogDPadInDigitalMode', conf.get('duckstation_digitalmode', 'false'))
            settings.set(pad_num, 'Analog', f'{sdl_num}/Guide')

        if ctrl_type == 'NeGcon':
            settings.set(pad_num, 'A',             f'{sdl_num}/B')
            settings.set(pad_num, 'B',             f'{sdl_num}/Y')
            settings.set(pad_num, 'I',             f'{sdl_num}/+RightTrigger')
            settings.set(pad_num, 'II',            f'{sdl_num}/+LeftTrigger')
            settings.set(pad_num, 'L',             f'{sdl_num}/LeftShoulder')
            settings.set(pad_num, 'R',             f'{sdl_num}/RightShoulder')
            settings.set(pad_num, 'SteeringLeft',  f'{sdl_num}/-LeftX')
            settings.set(pad_num, 'SteeringRight', f'{sdl_num}/+LeftX')

        if ctrl_type == 'PlayStationMouse':
            settings.set(pad_num, 'Right', f'{sdl_num}/B')
            settings.set(pad_num, 'Left',  f'{sdl_num}/A')

    settings.set('Console', 'Region', _conf_value(conf, 'duckstation_region', 'Auto'))
    settings.set('Console', 'EnableCheats', _conf_value(conf, 'duckstation_cheats', 'False'))
    settings.set('BIOS', 'SearchDirectory', '/userdata/bios')
    settings.set('BIOS', 'PatchFastBoot', _conf_value(conf, 'duckstation_PatchFastBoot', 'false'))
    settings.set('CPU', 'ExecutionMode', _conf_value(conf, 'duckstation_executionmode', 'Recompiler'))
    settings.set('GPU', 'Renderer', _conf_value(conf, 'duckstation_gfxbackend', 'OpenGL'))
    settings.set('GPU', 'PerSampleShading', 'false')
    settings.set('GPU', 'Multisamples', '1')
    settings.set('GPU', 'ThreadedPresentation', _conf_value(conf, 'duckstation_threadedpresentation', 'false'))
    settings.set('GPU', 'ResolutionScale', _conf_value(conf, 'duckstation_resolution_scale', '1'))
    settings.set('GPU', 'WidescreenHack', _conf_value(conf, 'duckstation_widescreen_hack', 'false'))
    settings.set('GPU', 'ForceNTSCTimings', _conf_value(conf, 'duckstation_60hz', 'false'))
    settings.set('GPU', 'TextureFilter', _conf_value(conf, 'duckstation_texture_filtering', 'Nearest'))
    pgxp = _conf_value(conf, 'duckstation_pgxp', 'true')
    settings.set('GPU', 'PGXPEnable', pgxp)
    settings.set('GPU', 'PGXPCulling', pgxp)
    settings.set('GPU', 'PGXPTextureCorrection', pgxp)
    settings.set('GPU', 'PGXPPreserveProjFP', pgxp)
    settings.set('GPU', 'TrueColor', _conf_value(conf, 'duckstation_truecolour', 'false'))
    settings.set('GPU', 'ScaledDithering', _conf_value(conf, 'duckstation_dithering', 'true'))
    settings.set('GPU', 'DisableInterlacing', _conf_value(conf, 'duckstation_interlacing', 'false'))
    settings.set('Display', 'AspectRatio', _conf_value(conf, 'duckstation_ratio', 'Auto (Game Native)'))
    settings.set('Display', 'VSync', _conf_value(conf, 'duckstation_vsync', 'false'))
    settings.set('Display', 'CropMode', _conf_value(conf, 'duckstation_CropMode', 'Overscan'))
    settings.set('Display', 'DisplayAllFrames', _conf_value(conf, 'duckstation_ofp', 'false'))
    settings.set('Display', 'ShowOSDMessages', _conf_value(conf, 'duckstation_osd', 'false'))
    settings.set('Display', 'IntegerScaling', _conf_value(conf, 'duckstation_integer', 'false'))
    settings.set('Display', 'LinearFiltering', _conf_value(conf, 'duckstation_linear', 'false'))
    settings.set('Display', 'Stretch', _conf_value(conf, 'duckstation_stretch', 'false'))
    settings.set('Audio', 'StretchMode', _conf_value(conf, 'duckstation_audio_mode', 'TimeStretch'))
    settings.set('GameList', 'RecursivePaths', '/userdata/roms/psx')
    settings.set('Hotkeys', 'FastForward', 'Keyboard/Tab')
    settings.set('Hotkeys', 'Reset', 'Keyboard/F6')
    settings.set('Hotkeys', 'LoadSelectedSaveState', 'Keyboard/F1')
    settings.set('Hotkeys', 'SaveSelectedSaveState', 'Keyboard/F2')
    settings.set('Hotkeys', 'SelectPreviousSaveStateSlot', 'Keyboard/F3')
    settings.set('Hotkeys', 'SelectNextSaveStateSlot', 'Keyboard/F4')
    settings.set('Hotkeys', 'Screenshot', 'Keyboard/F10')
    settings.set('Hotkeys', 'Rewind', 'Keyboard/F5')
    settings.set('Hotkeys', 'OpenPauseMenu', 'Keyboard/F7')
    settings.set('Hotkeys', 'ChangeDisc', 'Keyboard/F8')
    if settings.has_option('Hotkeys', 'OpenQuickMenu'):
        settings.remove_option('Hotkeys', 'OpenQuickMenu')

    if ctx.lightgun:
        gun_type = _gun_type(ctx)
        gun_count = max(1, min(8, len(ctx.controllers) or 1))
        for nplayer in range(1, gun_count + 1):
            pad_num = f'Pad{nplayer}'
            gun_num = f'Pointer-{nplayer - 1}'
            if gun_type == 'justifier':
                settings.set(pad_num, 'Type', 'Justifier')
            else:
                settings.set(pad_num, 'Type', 'GunCon')
                pedal_keys = {1: 'c', 2: 'v', 3: 'b', 4: 'n'}
                pedal = conf.get(f'controllers.pedals{nplayer}', pedal_keys.get(nplayer, ''))
                if pedal:
                    settings.set(pad_num, 'A', f'{gun_num}/RightButton & Keyboard/{pedal.upper()}')
                else:
                    settings.set(pad_num, 'A', f'{gun_num}/RightButton')
            settings.set(pad_num, 'CrosshairScale', _conf_value(conf, 'duckstation_crosshair', '0'))
            settings.set(pad_num, 'CrosshairColor', '0000FF' if nplayer == 1 else 'FF0000')

    with DUCKSTATION_SETTINGS.open('w', encoding='utf-8') as fh:
        settings.write(fh)

    _log.info("Wrote DuckStation config: %s", DUCKSTATION_SETTINGS)


def _launch_duckstation(ctx: LaunchContext) -> int:
    bin_path = _find_emulator_bin('duckstation-qt') or _find_emulator_bin('duckstation-nogui') or _find_emulator_bin('duckstation')
    if bin_path is None:
        _log.error("DuckStation not found")
        return 1

    (SAVES / ctx.system).mkdir(parents=True, exist_ok=True)
    _write_duckstation_config(ctx)

    conf = _load_hippos_conf()
    # Write SDL controller DB so DuckStation can identify controllers by GUID
    db_path = DUCKSTATION_CONFIG_DIR / 'game_controller_db.txt'
    db_path.write_text(generate_sdl_game_controller_config(ctx.controllers))

    if bin_path.name == 'duckstation-nogui':
        cmd = [str(bin_path), '-batch', '-fullscreen', '--', str(ctx.rom)]
    else:
        cmd = [str(bin_path), '-batch', '-nogui', '--', str(ctx.rom)]
    _log.info("Launching DuckStation: %s", ' '.join(cmd))

    env = _build_game_env(conf, ctx)
    env['SDL_JOYSTICK_HIDAPI'] = '0'
    result = _run_game_command(ctx, 'duckstation', cmd, env)
    return result.returncode


_FLYCAST_MAPPING_DIR = CONFIGS / 'flycast' / 'mappings'

_FLYCAST_HAT_CODES = {1: 256, 2: 259, 4: 257, 8: 258}  # ES hat value → Flycast code

_FLYCAST_DREAMCAST_MAP = {
    'up':            {'button': 'btn_dpad1_up',       'hat': 'btn_dpad1_up',       'axis': 'btn_dpad1_up'},
    'down':          {'button': 'btn_dpad1_down',     'hat': 'btn_dpad1_down'},
    'left':          {'button': 'btn_dpad1_left',     'hat': 'btn_dpad1_left',     'axis': 'btn_dpad1_left'},
    'right':         {'button': 'btn_dpad1_right',    'hat': 'btn_dpad1_right'},
    'joystick1left': {'axis': 'btn_analog_left'},
    'joystick1up':   {'axis': 'btn_analog_up'},
    'joystick2left': {'axis': 'axis2_left'},
    'joystick2up':   {'axis': 'axis2_up'},
    'b':             {'button': 'btn_a'},
    'a':             {'button': 'btn_b'},
    'y':             {'button': 'btn_x'},
    'x':             {'button': 'btn_y'},
    'l2':            {'axis': 'axis_trigger_left',    'button': 'btn_trigger_left'},
    'r2':            {'axis': 'axis_trigger_right',   'button': 'btn_trigger_right'},
    'start':         {'button': 'btn_start'},
}

_FLYCAST_ARCADE_MAP = {
    **_FLYCAST_DREAMCAST_MAP,
    'y':       {'button': 'btn_c'},
    'x':       {'button': 'btn_x'},
    'pageup':  {'button': 'btn_y'},
    'pagedown':{'button': 'btn_z'},
    'l3':      {'button': 'btn_dpad2_up'},
    'r3':      {'button': 'btn_dpad2_down'},
    'select':  {'button': 'btn_d'},
}

_FLYCAST_AXIS_OPPOSITE = {
    'joystick1left': 'btn_analog_right',
    'joystick1up':   'btn_analog_down',
    'joystick2left': 'axis2_right',
    'joystick2up':   'axis2_down',
    'up':            'btn_dpad1_down',
    'left':          'btn_dpad1_right',
}


def _write_flycast_controller_mapping(ctx: LaunchContext) -> None:
    """Write per-controller SDL_<name>.cfg mapping files for Flycast."""
    arcade_systems = {'naomi', 'naomi2', 'atomiswave', 'hikaru'}
    mapping = _FLYCAST_ARCADE_MAP if ctx.system in arcade_systems else _FLYCAST_DREAMCAST_MAP
    suffix = '_arcade' if ctx.system in arcade_systems else ''

    profiles = _load_es_input_configs()
    _FLYCAST_MAPPING_DIR.mkdir(parents=True, exist_ok=True)

    for ctrl in ctx.controllers:
        profile = _pick_es_profile(profiles, ctrl)
        if profile is None:
            continue

        cfg = configparser.ConfigParser(interpolation=None)
        for section in ('analog', 'digital', 'emulator'):
            cfg.add_section(section)

        analog_bind = 0
        digital_bind = 0

        for es_name, type_map in mapping.items():
            binding = profile.inputs.get(es_name)
            if binding is None:
                continue
            btype = binding.type
            if btype not in type_map:
                continue
            action = type_map[btype]

            if btype == 'hat':
                code = _FLYCAST_HAT_CODES.get(abs(binding.value), 256)
                cfg.set('digital', f'bind{digital_bind}', f'{code}:{action}')
                digital_bind += 1

            elif btype == 'button':
                cfg.set('digital', f'bind{digital_bind}', f'{binding.code}:{action}')
                digital_bind += 1

            elif btype == 'axis':
                # triggers use positive axis, sticks use negative (primary direction)
                sign = '+' if es_name in ('l2', 'r2') else '-'
                code = f'{binding.code}{sign}'
                cfg.set('analog', f'bind{analog_bind}', f'{code}:{action}')
                analog_bind += 1
                # write the opposite direction too
                opposite = _FLYCAST_AXIS_OPPOSITE.get(es_name)
                if opposite:
                    opp_sign = '+' if sign == '-' else '-'
                    cfg.set('analog', f'bind{analog_bind}', f'{binding.code}{opp_sign}:{opposite}')
                    analog_bind += 1

        cfg.set('emulator', 'dead_zone',     '10')
        cfg.set('emulator', 'mapping_name',  'Default')
        cfg.set('emulator', 'rumble_power',  '100')
        cfg.set('emulator', 'version',       '3')

        name = ctrl.name.replace('/', '_')
        cfg_path = _FLYCAST_MAPPING_DIR / f'SDL_{name}{suffix}.cfg'
        with cfg_path.open('w') as fh:
            cfg.write(fh)
        _log.info("Wrote Flycast controller mapping: %s", cfg_path)


def _write_flycast_config(ctx: LaunchContext) -> None:
    conf = _load_effective_hippos_conf()
    FLYCAST_CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    parser = _new_ini_parser()
    if FLYCAST_EMU_CFG.exists():
        parser.read(FLYCAST_EMU_CFG, encoding='utf-8')

    for section in ('input', 'config', 'window', 'achievements'):
        _ensure_section(parser, section)

    parser.set('window', 'fullscreen', 'yes')
    display_resolution = _display_resolution_from_conf(conf)
    if display_resolution is not None:
        width, height = display_resolution
        parser.set('window', 'width', str(width))
        parser.set('window', 'height', str(height))
    parser.set('config', 'rend.Resolution', _conf_value(conf, 'flycast_render_resolution', '480'))
    parser.set('config', 'rend.WideScreen', _conf_value(conf, 'flycast_ratio', 'no'))
    parser.set('config', 'rend.Rotate90', _conf_value(conf, 'flycast_rotate', 'no'))
    parser.set('config', 'rend.AnisotropicFiltering', _conf_value(conf, 'flycast_anisotropic', '1'))
    parser.set('config', 'rend.PerStripSorting', 'yes' if _conf_value(conf, 'flycast_sorting', '1') == '2' else 'no')
    parser.set('config', 'Dreamcast.Language', _conf_value(conf, 'flycast_language', '1'))
    parser.set('config', 'Dreamcast.Region', _conf_value(conf, 'flycast_region', '1'))
    parser.set('config', 'Dreamcast.AutoLoadState', _conf_value(conf, 'flycast_loadstate', 'no'))
    parser.set('config', 'Dreamcast.AutoSaveState', _conf_value(conf, 'flycast_savestate', 'no'))
    parser.set('config', 'Dreamcast.ForceWindowsCE', _conf_value(conf, 'flycast_winCE', 'no'))
    parser.set('config', 'PerGameVmu', _conf_value(conf, 'flycast_per_game_vmu', 'yes'))
    parser.set('config', 'aica.DSPEnabled', _conf_value(conf, 'flycast_DSP', 'no'))
    parser.set('config', 'rend.CrossHairColor1', _conf_value(conf, 'flycast_lightgun1_crosshair', _lightgun_color(1)))
    parser.set('config', 'rend.CrossHairColor2', _conf_value(conf, 'flycast_lightgun2_crosshair', _lightgun_color(2)))
    parser.set('config', 'rend.CrossHairColor3', _conf_value(conf, 'flycast_lightgun3_crosshair', _lightgun_color(3)))
    parser.set('config', 'rend.CrossHairColor4', _conf_value(conf, 'flycast_lightgun4_crosshair', _lightgun_color(4)))

    if ctx.lightgun:
        for nplayer in range(1, max(1, min(4, len(ctx.controllers) or 1)) + 1):
            parser.set('input', f'device{nplayer}', '7')
            parser.set('input', f'device{nplayer}.1', '1')
            parser.set('input', f'device{nplayer}.2', '10')
    else:
        for controller in ctx.controllers:
            parser.set('input', f'device{controller.player}', '0')
            parser.set('input', f'device{controller.player}.1', '1')
            parser.set('input', f'device{controller.player}.2', _conf_value(conf, f'flycast_ctrl{controller.player}_pack', '1'))
            parser.set('input', f'maple_sdl_joystick_{controller.index}', str(controller.player - 1))

    if _conf_bool(conf, 'global.retroachievements'):
        parser.set('achievements', 'Enabled', 'yes')
        parser.set('achievements', 'HardcoreMode', _conf_value(conf, 'global.retroachievements.hardcore', 'no'))
        parser.set('achievements', 'Token', _conf_value(conf, 'global.retroachievements.token', ''))
        parser.set('achievements', 'UserName', _conf_value(conf, 'global.retroachievements.username', ''))
    else:
        parser.set('achievements', 'Enabled', 'no')

    with FLYCAST_EMU_CFG.open('w', encoding='utf-8') as fh:
        parser.write(fh)

    _log.info("Wrote Flycast config: %s", FLYCAST_EMU_CFG)


def _launch_flycast(ctx: LaunchContext) -> int:
    bin_path = _find_emulator_bin('flycast')
    if bin_path is None:
        _log.error("flycast not found")
        return 1

    (SAVES / ctx.system).mkdir(parents=True, exist_ok=True)
    _write_flycast_config(ctx)
    _write_flycast_controller_mapping(ctx)

    conf = _load_hippos_conf()
    cmd = [str(bin_path), str(ctx.rom)]
    _log.info("Launching flycast: %s", ' '.join(cmd))

    env = _build_game_env(conf, ctx)
    env['SDL_JOYSTICK_HIDAPI'] = '0'
    result = _run_game_command(ctx, 'flycast', cmd, env)
    return result.returncode


def _sync_tree(source: Path, destination: Path) -> None:
    if not source.exists():
        return
    try:
        destination.resolve().relative_to(source.resolve())
        __import__('logging').getLogger('hippos.emulatorlauncher').error(
            "_sync_tree: destination %s is inside source %s — refusing to sync",
            destination, source,
        )
        return
    except ValueError:
        pass
    destination.mkdir(parents=True, exist_ok=True)
    cmp = filecmp.dircmp(source, destination)
    for name in cmp.left_only + cmp.diff_files:
        src_path = source / name
        dst_path = destination / name
        if src_path.is_dir():
            _sync_tree(src_path, dst_path)
        else:
            dst_path.parent.mkdir(parents=True, exist_ok=True)
            copyfile(src_path, dst_path)
    for name in cmp.common_dirs:
        _sync_tree(source / name, destination / name)


launch_mupen64plus_qt = _launch_mupen64plus_qt
launch_duckstation = _launch_duckstation
launch_flycast = _launch_flycast
