[global]
   workgroup = WORKGROUP
   server string = HippOS
   netbios name = HIPPOS
   security = user
   map to guest = bad user
   guest account = nobody
   log level = 1
   server role = standalone server
   load printers = no
   printing = bsd
   printcap name = /dev/null
   idmap config * : backend = tdb
   idmap config * : range = 1000-9999

[userdata]
   path = /userdata
   comment = HippOS User Data
   browseable = yes
   read only = no
   guest ok = yes
   create mask = 0664
   directory mask = 0775
   force user = nobody
