#!/bin/sh
PREREQ=""
prereqs() { echo "$PREREQ"; }
case "$1" in prereqs) prereqs; exit 0;; esac

. /usr/share/initramfs-tools/hook-functions

manual_add_modules overlay
copy_exec /sbin/blkid
copy_exec /bin/chown
copy_exec /bin/chmod
