FROM hippos-emulator-base:latest

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN=true

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        autoconf \
        autoconf-archive \
        automake \
        autopoint \
        bison \
        cargo \
        clang \
        cmake \
        curl \
        dbus \
        default-jdk-headless \
        dos2unix \
        xa65 \
        extra-cmake-modules \
        ffmpeg \
        flex \
        fluidsynth \
        fonts-dejavu-core \
        freeglut3-dev \
        g++ \
        gcc \
        gcc-multilib \
        gettext \
        git \
        glslang-dev \
        glslang-tools \
        golang-go \
        libaio-dev \
        libao-dev \
        libarchive-dev \
        libasound2-dev \
        libavcodec-dev \
        libavfilter-dev \
        libavformat-dev \
        libavif-dev \
        libavutil-dev \
        libbacktrace-dev \
        libbluetooth-dev \
        libboost-all-dev \
        libbz2-dev \
        libc6-dev-i386 \
        libcap-dev \
        libcereal-dev \
        libcubeb-dev \
        libcurl4-openssl-dev \
        libdbus-1-dev \
        libdecor-0-dev \
        libdisplay-info-dev \
        libdrm-dev \
        libegl-dev \
        libenet-dev \
        libepoxy-dev \
        libevdev-dev \
        libexpat1-dev \
        libfaad-dev \
        libfaudio-dev \
        libflac-dev \
        libfmt-dev \
        libfontconfig-dev \
        libfreetype-dev \
        libgbm-dev \
        libgl-dev \
        libgl1-mesa-dev \
        libgles2-mesa-dev \
        libglew-dev \
        libglm-dev \
        libglu1-mesa-dev \
        libglvnd-dev \
        libgtk-3-dev \
        libgudev-1.0-dev \
        libharfbuzz-dev \
        libhidapi-dev \
        libhowardhinnant-date-dev \
        libibus-1.0-dev \
        libinih-dev \
        libinput-dev \
        libjack-dev \
        libjpeg-dev \
        libluajit-5.1-dev \
        liblz4-dev \
        libmodplug-dev \
        libmpeg2-4-dev \
        libmpg123-dev \
        libncurses-dev \
        libogg-dev \
        libopenal-dev \
        libopengl-dev \
        libopus-dev \
        libopusfile-dev \
        libpcap-dev \
        libphysfs-dev \
        libpipewire-0.3-dev \
        libpixman-1-dev \
        libpng-dev \
        libportmidi-dev \
        libpugixml-dev \
        libpulse-dev \
        libcxxopts-dev \
        libreadline-dev \
        librtmidi-dev \
        libsamplerate0-dev \
        libsdl2-dev \
        libsdl2-gfx-dev \
        libsdl2-image-dev \
        libsdl2-mixer-dev \
        libsdl2-net-dev \
        libsdl2-ttf-dev \
        libsdl3-dev \
        libsdl3-image-dev \
        libsdl3-ttf-dev \
        libseat-dev \
        libserialport-dev \
        libshaderc-dev \
        libshaderc1 \
        libslirp-dev \
        libsndfile1-dev \
        libsoundtouch-dev \
        libspirv-cross-c-shared-dev \
        libspirv-cross-c-shared0 \
        libsqlite3-dev \
        libssl-dev \
        libstb-dev \
        libtomlplusplus-dev \
        libstdc++6 \
        libswresample-dev \
        libswscale-dev \
        libtheora-dev \
        libtool \
        libudev-dev \
        libusb-1.0-0-dev \
        libvorbis-dev \
        libvpx-dev \
        libvulkan-dev \
        libwayland-dev \
        libwayland-egl-backend-dev \
        libwebp-dev \
        libwxgtk3.2-dev \
        libx11-dev \
        libx11-xcb-dev \
        libeis-dev \
        liblcms2-dev \
        libxcb-composite0-dev \
        libxcb-errors-dev \
        libxcb-ewmh-dev \
        libxcb-icccm4-dev \
        libxcb-keysyms1-dev \
        libxcb-render0-dev \
        libxcb-res0-dev \
        libxcb-xfixes0-dev \
        libxcomposite-dev \
        libxcursor-dev \
        libxdamage-dev \
        libxext-dev \
        libxfixes-dev \
        libxi-dev \
        libxkbcommon-dev \
        libxkbcommon-x11-dev \
        libxml2-dev \
        libxmu-dev \
        libxrandr-dev \
        libxrender-dev \
        libxres-dev \
        libxss-dev \
        libxtst-dev \
        libxxf86vm-dev \
        libyaml-cpp-dev \
        libyaml-dev \
        libminizip-dev \
        libzarchive-dev \
        libzip-dev \
        libzstd-dev \
        lld \
        llvm \
        llvm-19 \
        llvm-19-dev \
        make \
        mesa-utils \
        nasm \
        ninja-build \
        nlohmann-json3-dev \
        p7zip-full \
        patchelf \
        pkg-config \
        pkgconf \
        portaudio19-dev \
        python3-pip \
        python3-tomli \
        python3-yaml \
        python3.13-venv \
        qtbase5-dev \
        qt6-base-dev \
        qt6-base-private-dev \
        qt6-multimedia-dev \
        qt6-svg-dev \
        qt6-tools-dev \
        qt6-tools-dev-tools \
        qt6-wayland \
        qt6-websockets-dev \
        rapidjson-dev \
        re2c \
        rustc \
        spirv-headers \
        spirv-tools \
        tcl-dev \
        udev \
        unzip \
        vim-common \
        wayland-protocols \
        xorg \
        xserver-xorg-core \
        xwayland \
        xxd \
        zip \
        zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key \
        -o /etc/apt/trusted.gpg.d/llvm.asc \
    && echo "deb https://apt.llvm.org/trixie/ llvm-toolchain-trixie-21 main" \
        > /etc/apt/sources.list.d/llvm-21.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        clang-21 \
        lld-21 \
        llvm-21 \
        libc++-21-dev \
        libc++abi-21-dev \
        libxinerama-dev \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain 1.88.0

ENV PATH="/root/.cargo/bin:${PATH}"
